package seedu.address.logic.commands;

import static java.util.Objects.requireNonNull;

import java.time.LocalDate;
import java.util.List;

import seedu.address.model.Model;
import seedu.address.model.order.OrderDeliveredAndFromDatePredicate;

/**
 * Finds and lists all delivered orders in the current day, and displays the total
 * revenue generated by the orders.
 */
public class RevenueCommand extends Command {
    public static final String COMMAND_WORD = "revenue";

    public static final String MESSAGE_USAGE = COMMAND_WORD + ": Finds the total revenue "
            + "of the current day "
            + "and displays related orders as a list with index numbers.\n"
            + "Parameters: KEYWORD\n"
            + "where KEYWORD is one of 'today'\n"
            + "Example: " + COMMAND_WORD + " today";

    public static final String MESSAGE_SUCCESS = "Total revenue: $";

    private final OrderDeliveredAndFromDatePredicate predicate = new OrderDeliveredAndFromDatePredicate(List.of(LocalDate.now()));

    @Override
    public CommandResult execute(Model model) {
        requireNonNull(model);
        model.updateFilteredOrderList(predicate);
        double revenue = model.getFilteredOrderList().stream()
                .mapToDouble(x -> x.getTotalPrice()).sum();
        return new CommandResult(MESSAGE_SUCCESS
                + String.format("%.2f", revenue), false, false, false, false, true);
    }

    @Override
    public boolean equals(Object other) {
        return other == this // short circuit if same object
                || (other instanceof RevenueCommand // instanceof handles nulls
                && predicate.equals(((RevenueCommand) other).predicate)); // state check
    }
}
